on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 0
          # optional: lock to your default branch explicitly
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nflreadpy polars

      - name: Run opportunity report
        run: |
          mkdir -p reports
          python data_loaders/opportunity_report.py 2025 --output-dir ./reports

      - name: Commit and push if changes
        shell: bash
        run: |
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Be resilient if no files match the glob
          shopt -s nullglob
          files=(reports/*.csv)
          if (( ${#files[@]} )); then
            git add "${files[@]}"
          else
            echo "No new CSVs to add."
          fi

          # Only commit when there are staged changes
          if ! git diff --staged --quiet; then
            git commit -m "Update opportunity reports - $(date +'%Y-%m-%d')"
            # Push from detached HEAD directly to main
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
