name: Weekly Opportunity Report

on:
  schedule:
    # Run every Tuesday at 8:00 AM UTC (adjust time as needed)
    - cron: '0 8 * * 2'
  workflow_dispatch: # Allows manual trigger from GitHub Actions tab

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nflreadpy polars
    
    - name: Run opportunity report
      run: |
        python opportunity_report.py all --output-dir ./reports
    
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add reports/*.csv
        git diff --staged --quiet || git commit -m "Update opportunity reports - $(date +'%Y-%m-%d')"
        git push
